services:
  postgres:
    image: postgres:16.2-alpine
    shm_size: 1g
    user: postgres
    restart: always
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    command: |
      postgres 
      -c wal_level=logical
      -c max_wal_senders=10 
      -c max_replication_slots=5 
      -c hot_standby=on 
      -c hot_standby_feedback=on
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/postgres/:/docker-entrypoint-initdb.d

  seeder:
    image: oven/bun:latest
    depends_on:
      - postgres
    volumes:
      - ./src/postgres/:/app
    working_dir: /app
    environment:
      - ZERO_UPSTREAM_DB=${ZERO_UPSTREAM_DB}
    command: sh -c "bun install && bun run seed.ts"

volumes:
  pgdata:
    driver: local
